### ISSUE TITLE
number validator cannot return false

### ISSUE THREAD

**Issue by zcong2333** [iresty/lua-resty-jsonschema#6]
>resty -e 'local jsonschema = require "resty.jsonschema"     local myvalidator = jsonschema.generate_validator {
>   type = 'object',
>   properties = {
>     foo = { type = 'string' },
>     bar = { type = 'number' },
>   },
> }
> 
> print(myvalidator{ foo='sss', bar=ppp }) '
true

>resty -e 'local jsonschema = require "resty.jsonschema"     local myvalidator jsonschema.generate_validator {
>   type = 'object',
>   properties = {
>     foo = { type = 'string' },
>     bar = { type = 'number' },
>   },
> }
> 
> print(myvalidator{ foo=111, bar=ppp })         '
falseproperty "foo" validation failed: wrong type: expected one of , got number

**Comment by membphis** [comment]
```lua
local jsonschema = require "resty.jsonschema"
local myvalidator = jsonschema.generate_validator {
    type = 'object',
    properties = {
        foo = { type = 'string' },
        bar = { type = 'number' },
    },
}

-- ppp is nil
print("1st: ", myvalidator({foo='sss', bar=ppp}))
print("2st: ", myvalidator({foo='sss'}))

local ppp = "sss"
print("3st: ", myvalidator({foo='sss', bar=ppp}))
```

```shell
+ resty test.lua
1st: true
2st: true
3st: falseproperty "bar" validation failed: wrong type: expected number, got string
```

**Comment by membphis** [comment]
```shell
$ cat test.lua
local jsonschema = require "resty.jsonschema"
local myvalidator = jsonschema.generate_validator {
    type = 'object',
    properties = {
        foo = { type = 'string' },
        bar = { type = 'number' },
    },
    required = {"foo", "bar"}
}

print("1st: ", myvalidator({foo='sss', bar=ppp}))
print("2st: ", myvalidator({foo='sss'}))

$ resty test.lua
```
